First home work
timac11/2018-FS-11-Frontend-Sokolov pull request #1
Opened 2018-10-10 21:51 UTC by timac11

2018-10-11 22:07 UTC, martinkomitsky commented on package.json
> +    "lint": "./node_modules/eslint/bin/eslint.js ./src/**"
Первый, кто додумался, это заявка на успех!

2018-10-11 22:09 UTC, martinkomitsky commented on src/lib/test.js
> +    let divElement = document.createElement("div");
Но, кажется, линтер сам ты не запускал и ошибки не проверял. Попробуй запустить `npm run lint` и исправить все

2018-10-11 22:09 UTC, martinkomitsky commented on src/lib/test.js
> +    let spanElement = document.createElement('span');
Это точно const

2018-10-11 22:10 UTC, martinkomitsky commented on src/lib/test.js
> +    let divElement = document.createElement("div");
const

2018-10-11 22:10 UTC, martinkomitsky requested changes
Исправить замечания

2018-10-12 03:31 UTC, timac11 commented on src/lib/test.js
> +    let divElement = document.createElement("div");
не,  запускал, но я не понимаю, почму линт не показвает, что тут двойнsе ковчки
![2018-10-12 06-28-46](https://user-images.githubusercontent.com/15220910/46846452-7000af80-cde8-11e8-9c35-d35bbf568205.png)

2018-10-12 03:37 UTC, timac11 commented on src/lib/test.js
> +    let divElement = document.createElement("div");
попавил

2018-10-12 03:37 UTC, timac11 commented on src/lib/test.js
> +    let spanElement = document.createElement('span');
поправил

2018-10-12 03:48 UTC, timac11 commented on src/lib/test.js
> +    let divElement = document.createElement("div");
@martinkomitsky в чём тут может быть проблема?

2018-10-12 08:35 UTC, martinkomitsky commented
https://github.com/frontend-track-mail-ru/homework/blob/master/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F%20%D0%B4%D0%BB%D1%8F%20%D1%81%D0%B4%D0%B0%D1%87%D0%B8%20%D0%94%D0%97.pdf
Так, выполни-ка все требования - имя репозитория непонятное

2018-10-12 08:37 UTC, martinkomitsky commented on src/lib/test.js
> +    let divElement = document.createElement("div");
@timac11 там же написано понятным языком. Нужно в конфигах eslint указать эту опцию

2018-10-12 08:44 UTC, timac11 commented on src/lib/test.js
> +    let divElement = document.createElement("div");
согласен, видимо, слепой))

2018-10-12 08:54 UTC, timac11 commented
@martinkomitsky исправил все замечания

2018-10-12 08:56 UTC, martinkomitsky commented
@timac11 теперь нет ошибок в при запуске линтера?

2018-10-12 09:09 UTC, timac11 commented
@martinkomitsky поправил) можно как-нибудь отключить пробелы и отступы? сейчас только ругается, что 4 пробела вместо табов, заменяю пробелы табами - тоже ругается

2018-10-12 09:15 UTC, martinkomitsky commented
Сохрани табы и запусти еще раз, ошибок быть не должно. Покажи скриншот с ошибками, если будут

2018-10-12 09:22 UTC, timac11 commented
Всё, щас ошибок нет

2018-10-12 09:26 UTC, merged

2018-10-12 09:26 UTC, martinkomitsky commented
10