Second home work
timac11/2018-FS-11-Frontend-Sokolov pull request #2
Opened 2018-10-20 20:22 UTC by timac11

2018-10-22 17:53 UTC, martinkomitsky requested changes
Такс, только я что-то пропустил, а где твой webpack.config? И как ты собираешь проект? 
Сделай, хотя бы, так, как сделано в примере Бориса. 
Webpack должен быть в зависимостях package.json, еще должен быть скрипт запуска сборки `build`.

2018-10-22 22:18 UTC, timac11 commented
Привет. добавил вебпак конфиг. Просто он не особо пока нужен был, поэтому, видимо, не добавлял. Здесь всё равно одна вёрстка пока)

2018-10-23 20:21 UTC, timac11 commented
@martinkomitsky нужно ли что-то ещё поправить?

2018-10-24 19:25 UTC, martinkomitsky commented
Сорри, за поздний ответ.
Да, надо бы поправить кое-какие вещи

2018-10-24 19:27 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/47455915-c653f200-d7db-11e8-879f-6a966e2eae24.png)
1. Непонятно, что тут с кнопкой отправки. Нужно текст добавить или иконку
2. Сообщения не отправляются. Нужно сверстать "балунчики" сообщений (входящих, исходящих) и выводить их по клику на кнопку или нажатии на enter

2018-10-30 18:50 UTC, merged

2018-10-30 18:50 UTC, martinkomitsky commented
Окей, 
![image](https://user-images.githubusercontent.com/14847018/47742481-ce091000-dc8d-11e8-958e-57d96d12132d.png)
Смержил, так как после срока, то 5.
Доделаешь эту ошибку в любом случае в след ДЗ, там без этого уже никак)