homefirst
timac11/2018-FS-11-Frontend-Sokolov pull request #8
Opened 2019-03-07 20:59 UTC by timac11

2019-03-09 14:21 UTC, martinkomitsky requested changes
1. Забыл добавить меня в assignee, случайно нашел твой реквест
2. Не ясно, что тут проверять, все в ошибках
![image](https://user-images.githubusercontent.com/14847018/54072719-b3742280-428f-11e9-9daf-b49211de7acf.png)

2019-03-11 22:49 UTC, timac11 commented
@martinkomitsky  поправил

2019-03-12 09:23 UTC, martinkomitsky approved these changes

2019-03-12 09:26 UTC, merged

2019-03-12 09:27 UTC, martinkomitsky commented
10 + bonus